name: tests
on:
  - push
  - pull_request
jobs:
  test-with-selenium:
    name: Test with Selenium
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull docker images
      run: tests/scripts/docker-compose.sh pull
    - name: Start test containers
      run: tests/scripts/docker-compose.sh up -d
    - name: Test selenium hub connection
      run: tests/scripts/docker-utils/test-connection.sh http://selenium-hub:4444
    # Start testing
    - name: Test default
      run: tests/scripts/docker-utils/exec-selenium.sh test_default.py
    - name: Test navigation
      run: tests/scripts/docker-utils/exec-selenium.sh test_navigation.py
    # Clean up
    - name: Stop test containers
      if: always()
      run: tests/scripts/docker-compose.sh shutdown
